[book]
src = "docs"
title = "Mythmallow"
language = "en"
multilingual = false
authors = [
    "Umut Åžahin <umutsahin@protonmail.com>",
    "Emre Baba <emrebaba0@protonmail.com>",
]

[build]
build-dir = "target/book"
create-missing = true
